version: "3.8"

services:
 db:
   image: mysql:latest
   container_name: drawingsAppContainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=drawings_app
   volumes:
     - db:\var\lib\mysql