CREATE DATABASE IF NOT EXISTS drawings_app;
USE drawings_app;

CREATE TABLE IF NOT EXISTS drawings (
    sessionId VARCHAR (255) NOT NULL,
    startX FLOAT,
    startY FLOAT,
    endX FLOAT,
    endY FLOAT,
    color VARCHAR(50) DEFAULT '#000000',
    width FLOAT DEFAULT 5,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    sessionId VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    is_banned BOOLEAN NOT NULL DEFAULT FALSE
);